export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCESS = 'CREATE_COURSE_SUCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";